In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv("test_scores.csv")
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [3]:
math_values = df['math'].values
math_values

array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67], dtype=int64)

In [4]:
cs_values= df['cs'].values
cs_values

array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73], dtype=int64)

In [9]:
reg = linear_model.LinearRegression()
reg.fit(df[['math']],df['cs'])

LinearRegression()

In [10]:
reg.coef_

array([1.01773624])

In [11]:
reg.intercept_

1.9152193111569176

In [12]:
math_2darr = df[['math']].values
cs_arr = df['cs'].values

In [13]:
reg = linear_model.LinearRegression()
reg.fit(math_2darr,cs_arr)

LinearRegression()